In [1]:
from tensorflow.keras.preprocessing.text import one_hot


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\sanja\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\sanja\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\sanja\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_lo

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\sanja\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\sanja\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\sanja\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_lo

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2420, 7748, 4033, 972],
 [2420, 7748, 4033, 8236],
 [2420, 6551, 4033, 2896],
 [2477, 499, 7123, 6392, 5770],
 [2477, 499, 7123, 6392, 2280],
 [1657, 2420, 116, 4033, 2440],
 [4911, 7118, 3715, 6392]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2420 7748 4033  972]
 [   0    0    0    0 2420 7748 4033 8236]
 [   0    0    0    0 2420 6551 4033 2896]
 [   0    0    0 2477  499 7123 6392 5770]
 [   0    0    0 2477  499 7123 6392 2280]
 [   0    0    0 1657 2420  116 4033 2440]
 [   0    0    0    0 4911 7118 3715 6392]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\sanja\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step


array([[[ 2.00754888e-02,  4.30688523e-02,  2.15079822e-02,
          1.56677850e-02,  9.51015949e-03, -3.95252556e-03,
         -4.99315262e-02, -4.61714342e-03,  2.95831226e-02,
          6.95078447e-03],
        [ 2.00754888e-02,  4.30688523e-02,  2.15079822e-02,
          1.56677850e-02,  9.51015949e-03, -3.95252556e-03,
         -4.99315262e-02, -4.61714342e-03,  2.95831226e-02,
          6.95078447e-03],
        [ 2.00754888e-02,  4.30688523e-02,  2.15079822e-02,
          1.56677850e-02,  9.51015949e-03, -3.95252556e-03,
         -4.99315262e-02, -4.61714342e-03,  2.95831226e-02,
          6.95078447e-03],
        [ 2.00754888e-02,  4.30688523e-02,  2.15079822e-02,
          1.56677850e-02,  9.51015949e-03, -3.95252556e-03,
         -4.99315262e-02, -4.61714342e-03,  2.95831226e-02,
          6.95078447e-03],
        [-6.66984171e-03,  2.88226940e-02, -4.65205796e-02,
          2.72548683e-02,  1.56774372e-03, -3.29636708e-02,
          1.57197379e-02,  1.10426657e-02,  1.145787

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 2420, 7748, 4033,  972], dtype=int32)

In [20]:
import numpy as np

# Add batch dimension
sample = np.expand_dims(embedded_docs[0], axis=0)

# Predict
prediction = model.predict(sample)
print(prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
[[[ 0.02007549  0.04306885  0.02150798  0.01566778  0.00951016
   -0.00395253 -0.04993153 -0.00461714  0.02958312  0.00695078]
  [ 0.02007549  0.04306885  0.02150798  0.01566778  0.00951016
   -0.00395253 -0.04993153 -0.00461714  0.02958312  0.00695078]
  [ 0.02007549  0.04306885  0.02150798  0.01566778  0.00951016
   -0.00395253 -0.04993153 -0.00461714  0.02958312  0.00695078]
  [ 0.02007549  0.04306885  0.02150798  0.01566778  0.00951016
   -0.00395253 -0.04993153 -0.00461714  0.02958312  0.00695078]
  [-0.00666984  0.02882269 -0.04652058  0.02725487  0.00156774
   -0.03296367  0.01571974  0.01104267  0.01145787 -0.0325873 ]
  [-0.00272274 -0.00153276  0.0128754  -0.01977125 -0.01398154
   -0.04854637  0.04021185 -0.04058852 -0.03126692 -0.04741479]
  [-0.02142019 -0.03047683 -0.00384944  0.03089129  0.01109474
   -0.01768776 -0.03905354  0.04750797 -0.0152806   0.03148396]
  [-0.02824583 -0.00684641  0.01628151 -0.04893495 -0.04736545
   -0.0031